Fix scaling issue
Esri/serlio pull request #101
Opened 2021-12-22 13:12 UTC by chr11115

- Scale geometry such that it uses proper units (prt uses meter, while maya uses centimeter -> scale difference of 100)

2022-01-05 14:00 UTC, mistafunk requested changes
(deleted wrong review comment)

2022-01-05 16:23 UTC, mistafunk requested changes
LGTM, but let's do the scaling in double precision to be on the safe side for big/small coordinates.

2022-01-06 14:21 UTC, chr11115 commented on src/serlio/modifiers/MayaCallbacks.cpp
> +		                     static_cast<float>(a[i * 3 + 2])) * mu::PRT_TO_SERLIO_SCALE,
fixed, using double precision now

2022-01-06 15:47 UTC, mistafunk approved these changes
LGTM, feel free to merge.

2022-01-06 16:15 UTC, merged