Cknieling/support dependent attributes
Esri/serlio pull request #105
Opened 2022-01-11 08:47 UTC by chr11115

- generate dynamic default values that depend on user set attributes
- add functionality to query dynamic default values for enums 
- minor improvements for setting attribute values

2022-01-13 11:06 UTC, mistafunk requested changes
Applying our favela.rpk example to a 10x10 quad (switch scene to meters first), now produces this warning:

[error] maya status error at .../serlio/src/serlio/modifiers/PRTModifierAction.cpp:896: (kFailure): Object does not exist (code 1)

the model is still generated but it seems this PR introduces some unexpected side-effects

2022-01-13 13:10 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierAction.cpp
> +                                           const PRTMesh& prtMesh, const int32_t seed, const AttributeMapUPtr& attributeMap) {
fixed

2022-01-13 13:10 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierAction.cpp
> +short getDefaultEnumValue(const AttributeMapUPtr& defaultAttributeValues, const MFnEnumAttribute& eAttr,
fixed

2022-01-13 13:10 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierNode.cpp
> +			const bool ruleFileWasChanged = rulePkgData.asString() != currentRulePkgData.asString();
fixed

2022-01-13 13:10 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierAction.cpp
> +				if (currBool == defBoolVal)
fixed, using `const bool currbool now`

2022-01-13 13:12 UTC, chr11115 commented
> Applying our favela.rpk example to a 10x10 quad (switch scene to meters first), now produces this warning:
> 
> [error] maya status error at .../serlio/src/serlio/modifiers/PRTModifierAction.cpp:896: (kFailure): Object does not exist (code 1)
> 
> the model is still generated but it seems this PR introduces some unexpected side-effects

Nice find, I will investigate the cause.

2022-01-14 15:20 UTC, mistafunk approved these changes
LGTM, I'll provide further cleanup suggestion in a separate PR

2022-01-14 15:55 UTC, merged