Cknieling/initial enum selection
Esri/serlio pull request #121
Opened 2022-02-15 15:15 UTC by chr11115

- Add support for custom default values in enums

2022-02-21 13:43 UTC, chr11115 commented
Related PR, that is based on this PR:
https://github.com/Esri/serlio/pull/126

2022-02-22 14:49 UTC, mistafunk requested changes
Nice work! Found two issues...

2022-02-23 09:05 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierAction.cpp
> +		std::vector<MString> enumOptions;
The array/vector is never directly fed to the Maya API and std::vector is a bit more readable to iterate over imo. However, if I would need to set the value of a stringArrayAttribute, I would definately use a MStringArray. Would you switch in this scenario?

2022-02-24 12:35 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierAction.cpp
> +		std::vector<MString> enumOptions;
Not using MString anyways now..

2022-02-24 12:35 UTC, chr11115 commented on src/serlio/modifiers/PRTModifierAction.cpp
> +		MCHECK(mu::setEnumOptions(fNode.name().asWChar(), eAttr.name().asWChar(), {}));
fixed in https://github.com/Esri/serlio/pull/126

2022-03-03 15:43 UTC, mistafunk approved these changes

2022-03-07 12:23 UTC, merged