Update serlio changelog
Esri/serlio pull request #134
Opened 2022-03-07 12:05 UTC by chr11115

Update serlio changelog

2022-03-31 13:14 UTC, mistafunk requested changes
Nice work, please sort the lists to what is important from an user point of view.

2022-03-31 13:14 UTC, mistafunk commented on doc/changelog.md
> +  * RPK Manual.
move these lines to the bottom, not that important for users

2022-03-31 13:14 UTC, mistafunk commented on doc/changelog.md
> +* Updated test framework and build system
move to separate section "Development"

2022-04-04 07:00 UTC, chr11115 commented on doc/changelog.md
> +* Improved rule attribute ordering. (matching CityEngine)
fixed.

2022-04-04 07:00 UTC, chr11115 commented on doc/changelog.md
> +* Updated test framework and build system
done.

2022-04-04 07:00 UTC, chr11115 commented on doc/changelog.md
> +* Only check out git repo once in Jenkins (#79)
removed.

2022-04-04 08:08 UTC, mistafunk approved these changes
LGTM

2022-04-04 11:00 UTC, merged