Cknieling/bundle installers
Esri/serlio pull request #144
Opened 2022-05-03 09:41 UTC by chr11115

- bundle all installers into one installer
- avoid using c_pack abstraction layer for wix
- directly call candle/light in ant script

2022-05-09 14:06 UTC, mistafunk requested changes
Nice work overall! See inline comments for a few issues...

2022-05-11 07:36 UTC, chr11115 commented on Jenkinsfile
> +		dir(path: 'build'){
done.

2022-05-11 07:36 UTC, chr11115 commented on deploy/serlio.wxs.in
> +						<Directory Id='INSTALLDIR' Name='serlio'>
added suffix back

2022-05-11 07:36 UTC, chr11115 commented on deploy/build.xml
> +			<filterset>
fixed and renamed token names

2022-05-11 07:37 UTC, chr11115 commented on build.ps1
> +    $folders = $BUILD_FOLDER, $TOOLS_FOLDER, $NINJA_FOLDER, $CMAKE_FOLDER, $WIX_FOLDER, $ARCHIVE_BUILD_FOLDER, $ARTIFACTS_FOLDER
removed all references to wix tools

2022-05-11 09:10 UTC, mistafunk requested changes
In PackageContents the tag `OnlineDocumentation` should point to `https://github.com/esri/serlio`

Also please remove all XML comments from that file including the header (it is not a cmake template anymore).

Afterwards, feel free to merge.

2022-05-11 11:49 UTC, merged