Switch rules instead of adding a second prt node
Esri/serlio pull request #90
Opened 2021-11-23 08:31 UTC by chr11115

2021-11-29 10:19 UTC, mistafunk requested changes
Small syntax error in the script.

2021-11-29 10:19 UTC, mistafunk commented on src/serlio/scripts/serlioCreateUI.mel
>  	if(size($rulePackage)) {
Similar as in #89, consider writing the explicit `>0` check here as well

2021-11-29 10:19 UTC, mistafunk commented on src/serlio/scripts/serlioCreateUI.mel
> +			if (!alreadyHasExistingPrtNode){
Missing `$` character, I think.

// Error: "F:/dev/git/serlio/install/scripts/serlioCreateUI.mel" line 70.34: Invalid use of Maya object "alreadyHasExistingPrtNode". //

2021-11-29 16:06 UTC, chr11115 commented
added type definition for string

2021-11-30 14:55 UTC, mistafunk approved these changes
LGTM, verified functionality with Maya 2020 on LInux. Feel free to merge.

2021-12-01 08:03 UTC, merged